mobike/cliente/urls.py
from django.urls import path
from cliente.views import *

app_name='cliente'

urlpatterns = [
    path('', inicio, name='inicio'),
    path('registrar_usuario/', registrar_usuario, name='registrar_usuario'),
    path('iniciar_sesion/', iniciar_sesion, name='iniciar_sesion'),
    path('perfil/', perfil, name="perfil"),
    path('editar_datos/<int:id>', editar_datos, name="editar_datos"),
    path('cambiar_tarjeta/<int:id>', cambiar_tarjeta, name="cambiar_tarjeta"),
    path('cambiar_contrasena/<int:id>', cambiar_contrasena, name="cambiar_contrasena"),
    path('cerrar_sesion/', cerrar_sesion, name="cerrar_sesion"),

]

mobike/mobike/urls.py
from django.contrib import admin
from django.urls import path, include
from cliente.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cliente.urls')),
    path('administrativo/', include('administrativo.urls')),
]

mobike/cliente/models.py
from django.db import models

class Cliente(models.Model):
    id=models.AutoField(primary_key=True)
    email=models.EmailField(max_length=30, unique=True)
    password=models.CharField(max_length=30)
    nombre=models.CharField(max_length=30)
    apellido=models.CharField(max_length=30)
    comuna=models.CharField(max_length=30)
    direccion=models.CharField(max_length=60)
    tarjeta_numero=models.IntegerField()
    tarjeta_mes=models.IntegerField()
    tarjeta_anio=models.IntegerField()
    tarjeta_codigo=models.IntegerField()

mobike/cliente/forms.py
from django import forms
from cliente.models import *

class ClienteFormulario(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['email', 'password', 'nombre', 'apellido', 'comuna', 'direccion','tarjeta_numero', 'tarjeta_mes', 'tarjeta_anio', 'tarjeta_codigo']

class ClienteIniciarSesion(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['email','password']

mobike/cliente/views.py
from django.shortcuts import render, redirect, HttpResponse
from cliente.forms import *


def inicio(request):
    return render(request, 'inicio.html')

def registrar_usuario(request):
    validador=False
    existe=False
    if request.method=='POST':
        form = ClienteFormulario(data=request.POST)
        email = request.POST.get('email')

        cliente_existe = Cliente.objects.filter(email=email)
        if cliente_existe:
            existe = True
            contexto = {'form': form,
                        'existe':existe}
            return render(request, 'cliente/registrarse.html', contexto)
        else:
            if form.is_valid():
                form.save()
                validador = True
                contexto = {'form': form,
                            'validador':validador}
                return render(request, 'cliente/registrarse.html', contexto)
        
    form = ClienteFormulario
    contexto = {'form':form}
    return render(request, 'cliente/registrarse.html', contexto)

def iniciar_sesion(request):
    return render(request, 'cliente/iniciar_sesion.html')

def perfil(request):
    if request.method=='POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        existe = Cliente.objects.filter(email=email).filter(password=password)
        if existe:
            cliente=existe.get()
            contexto = {'cliente':cliente}
            return render(request, 'cliente/perfil.html', contexto)
        else:
            contexto={'no_existe':True}
            return render(request, 'cliente/iniciar_sesion.html', contexto)
    return render(request, 'cliente/perfil.html')

def editar_datos(request, id):
    if request.method=='POST':
        email=request.POST.get('email')
        nombre=request.POST.get('nombre')
        apellido=request.POST.get('apellido')
        comuna=request.POST.get('comuna')
        direccion=request.POST.get('direccion')
        cliente=Cliente.objects.filter(id=id)
        cliente_perfil=Cliente.objects.filter(id=id).get
        cliente.update(email=email,
                        nombre=nombre,
                        apellido=apellido,
                        comuna=comuna,
                        direccion=direccion)
        contexto={'datos_modificados':True,
                  'cliente':cliente_perfil}
        return render(request, 'cliente/perfil.html', contexto)
    return redirect('cliente:perfil')

def cambiar_tarjeta(request, id):
    if request.method=='POST':
        tarjeta_numero=request.POST.get('tarjeta_numero')
        tarjeta_mes=request.POST.get('tarjeta_mes')
        tarjeta_anio=request.POST.get('tarjeta_anio')
        cliente=Cliente.objects.filter(id=id)
        cliente_perfil=Cliente.objects.filter(id=id).get
        cliente.update(tarjeta_numero=tarjeta_numero,
                        tarjeta_mes=tarjeta_mes,
                        tarjeta_anio=tarjeta_anio)
        contexto={'tarjeta_modificada':True,
                  'cliente':cliente_perfil}
        return render(request, 'cliente/perfil.html', contexto)
    return redirect('cliente:perfil')

def cambiar_contrasena(request, id):
    if request.method=='POST':
        passwordActual=request.POST.get('password')
        cliente_perfil=Cliente.objects.filter(id=id).get()
        valido=Cliente.objects.filter(id=id).filter(password=passwordActual)
        if valido:
            cliente=valido
            password_nueva=request.POST.get('password_nueva')
            password_nueva2=request.POST.get('password_nueva2')
            if password_nueva != password_nueva2:
                contexto={'password_valido':False,
                          'cliente':cliente_perfil}
                return render(request, 'cliente/perfil.html', contexto)
            else:
                cliente.update(password=password_nueva)
                contexto={'password_valido':True,
                          'cliente':cliente_perfil}
                return render(request, 'cliente/perfil.html', contexto)
        else:
            contexto={'password_correcto':False,
                      'cliente':cliente_perfil}
            return render(request, 'cliente/perfil.html', contexto)
    return redirect('cliente:perfil')

def cerrar_sesion(request):
    contexto={'sesion_cerrada':True}
    return render(request, 'inicio.html', contexto)

mobike/templates/cliente/iniciar_sesion.html
{% extends 'base.html' %}

{% block cuerpo %}
    <div class="col-12 text-center"><h4>Iniciar Sesión</h4></div>
    <hr>

    <div class="row">
        <div class="col-lg-4 col-md-4"></div>
        <div class="col-lg-4 col-md-4">
            <form style="padding: 3px;" action="{% url 'cliente:perfil' %}" method="POST">{% csrf_token %}
                {% if no_existe %}
                <div class="alert alert-danger" role="alert">
                    Email y/o Contraseña incorrectas
                </div>
                {% endif %}
                <div class="form-group">

                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Correo@ejemplo.com">
                </div>
                <div class="form-group">
                    <label for="password">Contraseña</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Ingresar contraseña">
                </div>
                <div class="col-12 text-center">
                    <button type="submit" class="btn btn-primary">Iniciar Sesion</button><br>
                    <a href="{% url 'cliente:registrar_usuario' %}">¿No tienes cuenta? Registrate</a><br>
                    <a onclick="alert('Función aun no disponible')" href="#">¿No puedes acceder a tu cuenta?</a>
                </div>
            </form>
        </div>
        <div class="col-lg-4 col-md-4"></div>
    </div>
    
{% endblock cuerpo %}

mobike/templates/cliente/perfil.html
{% extends 'base.html' %}

{% block linknav %}
<div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cliente:cerrar_sesion' %}">Cerrar Sesión</a>
      </li>
    </ul>
  </div>
{% endblock linknav %}

{% block cuerpo %}
<style>
    .boton{
        text-decoration: none;
        color: white;
    }
    .boton:hover{
        text-decoration: none;
        color: white;
    }
</style>


<div class="alert alert-primary" role="alert">Bienvenido {{cliente.nombre}} {{cliente.apellido}}</div>


<div class="row">
    <div class="col-lg-4 col-md-4"></div>
    <div class="col-lg-4 col-md-4 text-center">
    {% if password_correcto == False %}
    <div data-togle="modal" data-target="#modalContrasena" class="alert alert-danger" role="alert">
        Contraseña incorrecta
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% elif password_valido == False %}
    <div class="alert alert-danger" role="alert">
        La confirmacion de contraseña no coincide
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% elif password_valido == True %}
    <div class="alert alert-success" role="alert">
        Contraseña actualizada exitosamente
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% elif tarjeta_modificada %}
    <div class="alert alert-success" role="alert">
        Tarjeta verificada y actualizada exitosamente
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% elif datos_modificados %}
    <div class="alert alert-success" role="alert">
        Datos actualizados exitosamente
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    {% endif %}
    <div>
        <button class="btn btn-info">
            <a  onclick="alert('Función aun no disponible')" href="#" class="boton">Nuevo Viaje</a>
        </button><br><hr>
        <button class="btn btn-info">
            <a  onclick="alert('Función aun no disponible')" href="#" class="boton">Mis viajes</a>
        </button><br><hr>
        <button class="btn btn-info">
            <a  onclick="alert('Función aun no disponible')" href="#" class="boton">Buscar estacionamiento</a>
        </button><br><hr>
        <button class="btn btn-warning">
            <a href="{% url 'cliente:editar_datos' cliente.id %}" class="boton" data-toggle="modal" data-target="#modalEditar">Actualizar datos</a>
        </button><br><hr>
        <button class="btn btn-warning">
            <a href="{% url 'cliente:cambiar_tarjeta' cliente.id %}" class="boton" data-toggle="modal" data-target="#modalTarjeta">Cambiar tarjeta</a>
        </button><br><hr>
        <button class="btn btn-warning">
            <a href="{% url 'cliente:cambiar_contrasena' cliente.id %}" class="boton" data-toggle="modal" data-target="#modalContrasena">Cambiar contraseña</a>
        </button><br><hr>
        <button class="btn btn-danger">
            <a href="{% url 'cliente:cerrar_sesion' %}" class="boton">Cerrar Sesión</a>
        </button>
    </div>
<div class="col-lg-4 col-md-4"></div>
</div>


<!--MODAL ACTUALIZAR DATOS-->
<div class="modal fade" id="modalEditar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Actualizar Datos</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <form class="form-group" action="{% url 'cliente:editar_datos' cliente.id %}" method="POST">{% csrf_token %}
                <div class="form-group">
                    <label for="email">Email</label>
                    <input class="form-control" type="email" value="{{cliente.email}}" name="email" id="email" required>
                </div>
                <div class="form-group">
                    <label for="nombre">Nombre</label>
                    <input class="form-control" type="text" value="{{cliente.nombre}}" name="nombre" id="nombre" required>
                </div>
                <div class="form-group">
                    <label for="apellido">Apellido</label>
                    <input class="form-control" type="text" value="{{cliente.apellido}}" name="apellido" id="apellido" required>
                </div>
                <div class="form-group">
                    <label for="comuna">Comuna</label>
                    <select class="form-control" id="comuna" name="comuna" required>
                        {% if cliente.comuna == 'La Reina' %}
                            <option selected>{{cliente.comuna}}</option>
                            <option>Providencia</option>
                            <option>Ñuñoa</option>
                        {% elif cliente.comuna == 'Providencia' %}
                            <option selected>{{cliente.comuna}}</option>
                            <option>La Reina</option>
                            <option>Ñuñoa</option>
                        {% elif cliente.comuna == 'Ñuñoa' %}
                            <option selected>{{cliente.comuna}}</option>
                            <option>La Reina</option>
                            <option>Providencia</option>
                        {% endif %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="direccion">Direccion</label>
                    <input class="form-control" type="text" value="{{cliente.direccion}}" name="direccion" id="direccion" required>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-success">Actualizar</button>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>

  <!--MODAL CAMBIAR TARJETA-->
<div class="modal fade" id="modalTarjeta" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Cambiar Tarjeta</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <form class="form-group" action="{% url 'cliente:cambiar_tarjeta' cliente.id %}" method="POST">{% csrf_token %}
                <div class="form-group">
                    <label for="tarjeta_numero">Numero tarjeta</label>
                    <input class="form-control" type="number" value="{{cliente.tarjeta_numero}}" name="tarjeta_numero" id="tarjeta_numero">
                </div>
                <div class="form-group">
                    <label for="tarjeta_mes">Caducidad</label>
                    <div class="form-inline">
                        <input class="form-control col-3" type="number" value="{{cliente.tarjeta_mes}}" name="tarjeta_mes" id="tarjeta_mes" required>/
                        <input class="form-control col-3" type="number" value="{{cliente.tarjeta_anio}}" name="tarjeta_anio" id="tarjeta_anio" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="tarjeta_codigo">CVV</label>
                    <input class="form-control col-3" type="password" value="" name="tarjeta_codigo" id="tarjeta_codigo" required>
                </div>
                
                <div class="modal-footer">
                    <button type="submit" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-success">Verificar y actualizar</button>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>

  <!--MODAL CAMBIAR CONTRASEÑA-->
<div class="modal fade" id="modalContrasena" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Cambiar Contraseña</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <form class="form-group" action="{% url 'cliente:cambiar_contrasena' cliente.id %}" method="POST">{% csrf_token %}
                <div class="form-group">
                    <label for="password">Contraseña Actual</label>
                    <input class="form-control" type="password"  name="password" id="password" required>
                </div>
                <div class="form-group">
                    <label for="password_nueva">Contraseña Nueva</label>
                    <input class="form-control" type="password"  name="password_nueva" id="password_nueva" required>
                </div>
                <div class="form-group">
                    <label for="password_nueva2">Confirmar Contraseña</label>
                    <input class="form-control" type="password"  name="password_nueva2" id="password_nueva2" required>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-success">Cambiar contraseña</button>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>




{% endblock cuerpo %}

mobike/templates/cliente/registrarse.html
{% extends 'base.html' %}

{% block cuerpo %}

    <div class="col-12 text-center"><h4>Registro de Clientes</h4></div>
    <hr>

    
    
    <div class="row">
    <div class="col-lg-4 col-md-4"></div>
    <div class="col-lg-4 col-md-4">
        <form style="padding: 3px;" class="mx-auto" action="{% url 'cliente:registrar_usuario' %}" method="POST">{% csrf_token %}
            {% if validador %}
            <div class="alert alert-success" role="alert">
                Registro completado exitosamente
            </div>
            {% endif %}
            {% if existe %}
            <div class="alert alert-danger" role="alert">
                El correo ingresado ya se encuentra registrado
            </div>
            {% endif %}
            <div class="form-group mx-auto">
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Correo@ejemplo.com" required>
            </div>
            <div class="form-group">
                <label for="password">Contraseña</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Ingresar contraseña" required>
            </div>
            <div class="form-group">
                <label for="nombre">Nombre</label>
                <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Ingresar nombre" required>
            </div>
            <div class="form-group">
                <label for="apellido">Apellido</label>
                <input type="text" class="form-control" id="apellido" name="apellido" placeholder="Ingresar apellido" required>
            </div>
            <div class="form-group">
                <label for="comuna">Comuna</label>
                <select class="form-control" id="comuna" name="comuna" required>
                    <option>La Reina</option>
                    <option>Providencia</option>
                    <option>Ñuñoa</option>
                </select>
                </div>
            <div class="form-group">
                <label for="direccion">Dirección</label>
                <input type="text" class="form-control" id="direccion" name="direccion" placeholder="Ingresar direccion" required>
            </div>
            <div class="form-group">
                <label for="tarjeta_numero">Numero Tarjeta</label>
                <input type="number" class="form-control" id="tarjeta_numero" name="tarjeta_numero" placeholder="Ingresar numero de tarjeta" required>
            </div>
            <div class="form-group">
                <label for="tarjeta_mes">Caducidad</label><br>
                <input type="number" style="display: inline-block" class="form-control col-5" id="tarjeta_mes" name="tarjeta_mes" placeholder="MM" required>
                / <input type="number" style="display: inline-block" class="form-control col-5" id="tarjeta_anio" name="tarjeta_anio" placeholder="AA" required>
            </div class="form-control">
                <label for="tarjeta_codigo">Código</label>
                <input type="password" class="form-control col-4" id="tarjeta_codigo" name="tarjeta_codigo" placeholder="CVV" required>
            </div>
            <div class="col-12 text-center">
                <hr>
                <button type="submit" class="btn btn-primary">Registrarse</button><br>
                <a href="{% url 'cliente:iniciar_sesion' %}">¿Tienes cuenta? Inicia Sesión</a><br>
            </div>
        </form>
        <div class="col-lg-4 col-md-4"></div>
    </div>
    </div>

{% endblock cuerpo%}