mobike/administrativo/urls.py
from django.urls import path
from administrativo.views import *

app_name='administrativo'

urlpatterns = [
    path('administrador_usuarios/', administrador_usuarios, name='administrador_usuarios'),
    path('iniciar_sesion/', iniciar_sesion, name='iniciar_sesion'),
    path('perfil/', perfil, name="perfil"),
    path('administracion_usuarios/', administrador_usuarios, name='administracion_usuarios'),
    path('eliminar_cliente/<int:id>', eliminar_cliente, name='eliminar_cliente'),
    path('editar_usuario/<int:id>', editar_usuario, name='editar_usuario'),
    path('buscar_id/', buscar_id, name='buscar_id'),
    path('registrar_usuario/', registrar_usuario, name="registrar_usuario"),
    path('registrar_administrativo/', registrar_administrativo, name="registrar_administrativo"),
    path('ver_administrativos/', ver_administrativos, name="ver_administrativos"),
    path('cerrar_sesion/', cerrar_sesion, name="cerrar_sesion"),
]

mobike/cliente/urls.py
from django.urls import path
from cliente.views import *

app_name='cliente'

urlpatterns = [
    path('', inicio, name='inicio'),
    path('registrar_usuario/', registrar_usuario, name='registrar_usuario'),
    path('iniciar_sesion/', iniciar_sesion, name='iniciar_sesion'),
    path('perfil/', perfil, name="perfil"),
    path('editar_datos/<int:id>', editar_datos, name="editar_datos"),
    path('cambiar_tarjeta/<int:id>', cambiar_tarjeta, name="cambiar_tarjeta"),
    path('cambiar_contrasena/<int:id>', cambiar_contrasena, name="cambiar_contrasena"),
    path('cerrar_sesion/', cerrar_sesion, name="cerrar_sesion"),

]

mobike/mobike/urls.py
from django.contrib import admin
from django.urls import path, include
from cliente.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cliente.urls')),
    path('administrativo/', include('administrativo.urls')),
]

mobike/administrativo/models.py
from django.db import models

class Administrativo(models.Model):
    id=models.AutoField(primary_key=True)
    email=models.EmailField(max_length=30, unique=True)
    password=models.CharField(max_length=30)
    nombre=models.CharField(max_length=30)
    apellido=models.CharField(max_length=30)

mobike/administrativo/forms.py
from django import forms
from administrativo.models import *

class AdministrativoFormulario(forms.ModelForm):
    class Meta:
        model = Administrativo
        fields = ['email', 'password', 'nombre', 'apellido']

class AdministrativoIniciarSesion(forms.ModelForm):
    class Meta:
        model = Administrativo
        fields = ['email','password']

mobike/administrativo/views.py
from django.shortcuts import render, HttpResponse, redirect, HttpResponseRedirect
from cliente.models import *
from administrativo.forms import *
from cliente.forms import *



def iniciar_sesion(request):
    return render(request, 'administrativo/iniciar_sesion.html')

def perfil(request):
    if request.method=='POST':
        email = request.POST.get('email')
        password= request.POST.get('password')
        existe = Administrativo.objects.filter(email=email).filter(password=password)
        if existe:
            administrativo=existe.get()
            contexto={'administrativo':administrativo}
            return render(request, 'administrativo/perfil.html', contexto)
        else:
            contexto={'no_existe':True}
            return render(request, 'administrativo/iniciar_sesion.html', contexto)
    return render(request, 'administrativo/perfil.html')

def administrador_usuarios(request):
    clientes = Cliente.objects.all()
    contexto = {'clientes':clientes}
    if request.method=='POST':
        return render(request, 'administrativo/administrador_usuarios.html', contexto)
    return render(request, 'administrativo/administrador_usuarios.html', contexto)
    

def eliminar_cliente(request, id):
    cliente = Cliente.objects.get(id=id)
    clientes = Cliente.objects.all()
    cliente.delete()
    validador_borrado=True
    contexto={'validador_borrado':validador_borrado,
              'clientes':clientes}
    return render(request, 'administrativo/administrador_usuarios.html', contexto)

def editar_usuario(request, id):
    if request.method=='POST':
        email=request.POST.get('email')
        nombre=request.POST.get('nombre')
        apellido=request.POST.get('apellido')
        comuna=request.POST.get('comuna')
        direccion=request.POST.get('direccion')
        cliente = Cliente.objects.filter(id=id)
        cliente.update(email=email, nombre=nombre, apellido=apellido, comuna=comuna, direccion=direccion)
        validador_actualizar=True
        contexto={'validador_actualizar':validador_actualizar}
        return redirect('administrativo:administrador_usuarios')
    return redirect('administrativo:administrador_usuarios')

def buscar_id(request):
    if request.method=='POST':
        idBuscar=request.POST.get('idBuscar')
        existe=Cliente.objects.filter(id=idBuscar)
        if existe:
            cliente = existe.get()
            contexto={'cliente':cliente,
                      'existe':True}
            return render(request, 'administrativo/buscar_id.html', contexto)
        else:
            contexto={'existe':False,
                      'idBuscado':idBuscar}
            return render(request, 'administrativo/buscar_id.html', contexto)

    return render(request, 'administrativo/buscar_id.html')

def registrar_usuario(request):
    validador=False
    existe=False
    if request.method=='POST':
        form = ClienteFormulario(data=request.POST)
        email = request.POST.get('email')

        cliente_existe = Cliente.objects.filter(email=email)
        if cliente_existe:
            existe = True
            contexto = {'existe':existe}
            return render(request, 'administrativo/perfil.html', contexto)
        else:
            if form.is_valid():
                form.save()
                validador = True
                contexto = {'validador':validador}
                return render(request, 'administrativo/perfil.html', contexto)
                return redirect()
    return render(request, 'administrativo/perfil.html')

def registrar_administrativo(request):
    validador=False
    existe=False
    if request.method=='POST':
        form = AdministrativoFormulario(data=request.POST)
        email = request.POST.get('email')

        administrativo_existe = Administrativo.objects.filter(email=email)
        if administrativo_existe:
            existe = True
            contexto = {'existe_administrativo':existe}
            return render(request, 'administrativo/perfil.html', contexto)
        else:
            if form.is_valid():
                form.save()
                validador = True
                contexto = {'validador_administrativo':validador}
                return render(request, 'administrativo/perfil.html', contexto)
                return redirect()
    return render(request, 'administrativo/perfil.html')

def ver_administrativos(request):
    administrativos = Administrativo.objects.all()
    contexto = {'administrativos':administrativos}
    if request.method=='POST':
        return render(request, 'administrativo/ver_administrativos.html', contexto)
    return render(request, 'administrativo/ver_administrativos.html', contexto)

def cerrar_sesion(request):
    contexto={'sesion_cerrada':True}
    return render(request, 'inicio.html', contexto)

mobike/templates/administrativo/administrador_usuarios.html
{% extends 'base.html' %}

{% block linknav %}
<div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'administrativo:perfil' %}">Perfil</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'administrativo:administrador_usuarios' %}">Administrador de Clientes</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'administrativo:ver_administrativos' %}">Ver Administrativos</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'administrativo:cerrar_sesion' %}">Cerrar Sesión</a>
    </li>
  </ul>
</div>
{% endblock linknav %}

{% block cuerpo %}
  <form class="form-inline" action="{% url 'administrativo:buscar_id' %}" method="POST">{% csrf_token %}
    <input class="form-control mr-sm-2" type="number" placeholder="Ingresar id" aria-label="Search" id="idBuscar" name="idBuscar" required>
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar por id</button>
  </form>
<br>
{% if validador_borrado %}
<div class="alert alert-success" role="alert">
    Cliente Eliminado Exitosamente
</div>
{% endif %}

<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Email</th>
      <th scope="col">Nombre</th>
      <th scope="col">Apellido</th>
      <th scope="col">Opciones</th>
    </tr>
  </thead>
  <tbody>
    {% for cliente in clientes %}
          <tr>
            <td>{{cliente.id}}</td>
            <td>{{cliente.email}}</td>
            <td>{{cliente.nombre}}</td>
            <td>{{cliente.apellido}}</td>
            <td>
              <a href="#" data-toggle="modal" data-target="#modalActualizar{{cliente.id}}" style="color: green;">Editar</a>
              <a href="#" data-toggle="modal" data-target="#modalEliminar{{cliente.id}}" style="color: red;"><strong>Eliminar</strong> </a>
            </td>
          </tr>
          
          <!--MODAL ELIMINAR-->
            <div class="modal fade" id="modalEliminar{{cliente.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Eliminar</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      ¿Está seguro que desea eliminar al cliente <strong>{{cliente.nombre}} {{cliente.apellido}}</strong>?
                    </div>
                    <div class="modal-footer">
                      <button type="submit" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                      <button type="submit" class="btn btn-danger"><a style="text-decoration: none; color: white;" href="{% url 'administrativo:eliminar_cliente' cliente.id %}">Eliminar</a></button>
                    </div>
                  </div>
                </div>
              </div>
              
              <!--MODAL EDITAR-->
            <div class="modal fade" id="modalActualizar{{cliente.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Editar datos</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <!--FORM DENTRO DE MODAL-->
                  <div class="modal-body">

                    <form class="form-group" action="{% url 'administrativo:editar_usuario' cliente.id %}" method="POST">{% csrf_token %}
                      <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" class="form-control" id="email" name="email" value="{{cliente.email}}" placeholder="Correo@ejemplo.com" required>
                      </div>
                      <div class="form-group">
                        <label for="nombre">Nombre</label>
                        <input type="text" class="form-control" id="nombre" name="nombre" value="{{cliente.nombre}}" placeholder="Ingresar nombre" required>
                      </div>
                    <div class="form-group">
                      <label for="apellido">Apellido</label>
                      <input type="text" class="form-control" id="apellido" name="apellido" value="{{cliente.apellido}}" placeholder="Ingresar apellido" required>
                    </div>
                    
                    <div class="form-group">
                      <label for="comuna">Comuna</label>
                      <select class="form-control" id="comuna" name="comuna" required>
                          {% if cliente.comuna == 'La Reina' %}
                          <option selected>{{cliente.comuna}}</option>
                          <option>Providencia</option>
                              <option>Ñuñoa</option>
                          {% elif cliente.comuna == 'Providencia' %}
                          <option selected>{{cliente.comuna}}</option>
                              <option>La Reina</option>
                              <option>Ñuñoa</option>
                          {% elif cliente.comuna == 'Ñuñoa' %}
                          <option selected>{{cliente.comuna}}</option>
                          <option>La Reina</option>
                          <option>Providencia</option>
                              {% endif %}
                            </select>
                      </div>
                      <div class="form-group">
                        <label for="direccion">Dirección</label>
                        <input type="text" class="form-control" id="direccion" name="direccion" value="{{cliente.direccion}}" placeholder="Ingresar direccion" required>
                      </div>
                    </div>
                    <div class="col-12 text-center modal-footer">
                      <hr>
                        <button type="submit" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-success">Modificar</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </tbody>
      {% endfor %}
      </table>

            
{% endblock cuerpo %}

            

mobike/templates/administrativo/buscar_id.html
{% extends 'base.html' %}

{% block linknav %}
<div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'administrativo:perfil' %}">Perfil</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'administrativo:administrador_usuarios' %}">Administrador de Clientes</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'administrativo:ver_administrativos' %}">Ver Administrativos</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'administrativo:cerrar_sesion' %}">Cerrar Sesión</a>
    </li>
  </ul>
</div>
{% endblock linknav %}

{% block cuerpo %}
<form class="form-inline" action="{% url 'administrativo:buscar_id' %}" method="POST">{% csrf_token %}
  <input class="form-control mr-sm-2" type="number" placeholder="Ingresar id" aria-label="Search" id="idBuscar" name="idBuscar" required>
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar por id</button> 
  <button class="btn btn-outline-secondary btn-secondary"><a style="text-decoration: none; color:black;" href="{% url 'administrativo:administrador_usuarios' %}">Mostrar todos</a></button>
</form>
{% if validador_borrado %}
<div class="alert alert-success" role="alert">
    Cliente Eliminado Exitosamente
</div>
{% endif %}

{% if existe %}

<table class="table">
    <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Email</th>
            <th scope="col">Nombre</th>
            <th scope="col">Apellido</th>
            <th scope="col">Opciones</th>
        </tr>
    </thead>
    <tbody>
            <tr>
            <td>{{cliente.id}}</td>
            <td>{{cliente.email}}</td>
            <td>{{cliente.nombre}}</td>
            <td>{{cliente.apellido}}</td>
            <td>
              <a href="#" data-toggle="modal" data-target="#modalActualizar" style="color: green;">Editar</a>
            <a href="#" data-toggle="modal" data-target="#modalEliminar" style="color: red;"><strong>Eliminar</strong> </a>
            </td>
            </tr>
    </tbody>
</table>

<!--MODAL ELIMINAR-->
<div class="modal fade" id="modalEliminar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Eliminar</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          ¿Está seguro que desea eliminar al cliente <strong>{{cliente.nombre}} {{cliente.apellido}}</strong>?
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-danger"><a style="text-decoration: none; color: white;" href="{% url 'administrativo:eliminar_cliente' cliente.id %}">Eliminar</a></button>
        </div>
      </div>
    </div>
  </div>

  <!--MODAL ACTUALIZAR-->
  <div class="modal fade" id="modalActualizar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Editar datos</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <!--FORM DENTRO DE MODAL-->
        <div class="modal-body">

          <form class="form-group" action="{% url 'administrativo:editar_usuario' cliente.id %}" method="POST">{% csrf_token %}
            <div class="form-group">
              <label for="email">Email</label>
              <input type="email" class="form-control" id="email" name="email" value="{{cliente.email}}" placeholder="Correo@ejemplo.com" required>
            </div>
            <div class="form-group">
              <label for="nombre">Nombre</label>
              <input type="text" class="form-control" id="nombre" name="nombre" value="{{cliente.nombre}}" placeholder="Ingresar nombre" required>
            </div>
          <div class="form-group">
            <label for="apellido">Apellido</label>
              <input type="text" class="form-control" id="apellido" name="apellido" value="{{cliente.apellido}}" placeholder="Ingresar apellido" required>
          </div>
          
          <div class="form-group">
            <label for="comuna">Comuna</label>
            <select class="form-control" id="comuna" name="comuna" required>
                {% if cliente.comuna == 'La Reina' %}
                <option selected>{{cliente.comuna}}</option>
                    <option>Providencia</option>
                    <option>Ñuñoa</option>
                {% elif cliente.comuna == 'Providencia' %}
                <option selected>{{cliente.comuna}}</option>
                    <option>La Reina</option>
                    <option>Ñuñoa</option>
                {% elif cliente.comuna == 'Ñuñoa' %}
                <option selected>{{cliente.comuna}}</option>
                <option>La Reina</option>
                    <option>Providencia</option>
                    {% endif %}
              </select>
            </div>
            <div class="form-group">
              <label for="direccion">Dirección</label>
              <input type="text" class="form-control" id="direccion" name="direccion" value="{{cliente.direccion}}" placeholder="Ingresar direccion" required>
            </div>
          </div>
          <div class="col-12 text-center modal-footer">
              <hr>
              <button type="submit" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
              <button type="submit" class="btn btn-success">Modificar</button>
          </div>
        </form>
      </div>
    </div>
  </div>


{% else %}
<div class="alert alert-danger" role="alert">
    No se encontró ningun usuario con id: {{idBuscado}}
</div>
{% endif %}


{% endblock cuerpo %}

mobike/templates/administrativo/perfil.html
{% extends 'base.html' %}

{% block linknav %}
<div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'administrativo:perfil' %}">Perfil</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'administrativo:administrador_usuarios' %}">Administrador de Clientes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'administrativo:ver_administrativos' %}">Ver Administrativos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'administrativo:cerrar_sesion' %}">Cerrar Sesión</a>
      </li>
    </ul>
  </div>
{% endblock linknav %}



{% block cuerpo %}
<style>
    .boton{
        text-decoration: none;
        color: white;
    }
    .boton:hover{
        text-decoration: none;
        color: white;
    }
</style>

{% if validador == True %}
<div class="alert alert-success" role="alert">Cliente creado exitosamente
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% elif existe == True %}
<div class="alert alert-danger" role="alert">El email que intenta registrar ya se encuentra registrado
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% elif existe_administrativo %}
<div class="alert alert-danger" role="alert">El email de administrativo que intenta registrar ya se encuentra registrado
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% elif validador_administrativo %}
<div class="alert alert-success" role="alert">Nuevo administrativo registrado exitosamente
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% else %}
<div class="alert alert-primary" role="alert">Bienvenido {{administrativo.nombre}} {{administrativo.apellido}}</div>
{% endif %}

<div class="row">
    <div class="col-lg-4 col-md-4"></div>
    <div class="col-lg-4 col-md-4 text-center">
        <button class="btn btn-info">
            <a class="boton" href="{% url 'administrativo:administracion_usuarios' %}">Administrador de Clientes</a>
        </button><br><hr>
        <button class="btn btn-info">
            <a href="{% url 'administrativo:registrar_usuario' %}" class="boton" data-toggle="modal" data-target="#modalCliente">Crear Nuevo Cliente</a>
        </button><br><hr>
        <button class="btn btn-info">
            <a href="{% url 'administrativo:registrar_administrativo' %}" class="boton" data-toggle="modal" data-target="#modalAdministrativo">Crear Nuevo Administrativo</a>
        </button><br><hr>
        <button class="btn btn-info">
            <a class="boton" href="{% url 'administrativo:ver_administrativos' %}">Ver Administrativos</a>
        </button><br><hr>
        <button class="btn btn-info">
            <a  onclick="alert('Función aun no disponible')" href="#" class="boton">Generar Reportes</a>
        </button><br><hr>
        <button class="btn btn-danger">
            <a href="{% url 'cliente:cerrar_sesion' %}" class="boton">Cerrar Sesión</a>
        </button>
    </div>
    <div class="col-lg-4 col-md-4"></div>
</div>

<!--MODAL CREAR NUEVO CLIENTE-->
<div class="modal fade" id="modalCliente" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Crear Nuevo Cliente</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <form style="padding: 3px;" class="mx-auto" action="{% url 'administrativo:registrar_usuario' %}" method="POST">{% csrf_token %}
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Correo@ejemplo.com" required>
                </div>
                <div class="form-group">
                    <label for="password">Contraseña</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Ingresar contraseña" required>
                </div>
                <div class="form-group">
                    <label for="nombre">Nombre</label>
                    <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Ingresar nombre" required>
                </div>
                <div class="form-group">
                    <label for="apellido">Apellido</label>
                    <input type="text" class="form-control" id="apellido" name="apellido" placeholder="Ingresar apellido" required>
                </div>
                <div class="form-group">
                    <label for="comuna">Comuna</label>
                    <select class="form-control" id="comuna" name="comuna" required>
                        <option>La Reina</option>
                        <option>Providencia</option>
                        <option>Ñuñoa</option>
                    </select>
                    </div>
                <div class="form-group">
                    <label for="direccion">Dirección</label>
                    <input type="text" class="form-control" id="direccion" name="direccion" placeholder="Ingresar direccion" required>
                </div>
                <div class="form-group">
                    <label for="tarjeta_numero">Numero Tarjeta</label>
                    <input type="number" class="form-control" id="tarjeta_numero" name="tarjeta_numero" placeholder="Ingresar numero de tarjeta" required>
                </div>
                <div class="form-group">
                    <label for="tarjeta_mes">Caducidad</label><br>
                    <input type="number" style="display: inline-block" class="form-control col-5" id="tarjeta_mes" name="tarjeta_mes" placeholder="MM" required>
                    / <input type="number" style="display: inline-block" class="form-control col-5" id="tarjeta_anio" name="tarjeta_anio" placeholder="AA" required>
                </div class="form-control">
                    <label for="tarjeta_codigo">Código</label>
                    <input type="password" class="form-control col-4" id="tarjeta_codigo" name="tarjeta_codigo" placeholder="CVV" required>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Registrar</button><br>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>

  <!--MODAL CREAR NUEVO ADMINISTRATIVO-->
<div class="modal fade" id="modalAdministrativo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Crear Nuevo Administrativo</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <form style="padding: 3px;" class="mx-auto" action="{% url 'administrativo:registrar_administrativo' %}" method="POST">{% csrf_token %}
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Correo@ejemplo.com" required>
                </div>
                <div class="form-group">
                    <label for="password">Contraseña</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Ingresar contraseña" required>
                </div>
                <div class="form-group">
                    <label for="nombre">Nombre</label>
                    <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Ingresar nombre" required>
                </div>
                <div class="form-group">
                    <label for="apellido">Apellido</label>
                    <input type="text" class="form-control" id="apellido" name="apellido" placeholder="Ingresar apellido" required>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Registrar</button><br>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>

{% endblock cuerpo %}

mobike/templates/administrativo/ver_administrativos.html
{% extends 'base.html' %}

{% block linknav %}
<div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'administrativo:perfil' %}">Perfil</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'administrativo:administrador_usuarios' %}">Administrador de Clientes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'administrativo:ver_administrativos' %}">Ver Administrativos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'administrativo:cerrar_sesion' %}">Cerrar Sesión</a>
      </li>
    </ul>
  </div>
{% endblock linknav %}

{% block cuerpo %}

<table class="table">
    <thead>
        <tr>
        <th scope="col">id</th>
        <th scope="col">Email</th>
        <th scope="col">Nombre</th>
        <th scope="col">Apellido</th>
        </tr>
    </thead>
    {% for administrativo in administrativos %}
    <tbody>
        <tr>
            <td>{{administrativo.id}}</td>
            <td>{{administrativo.email}}</td>
            <td>{{administrativo.nombre}}</td>
            <td>{{administrativo.apellido}}</td>
        </tr>
    </tbody>
    {% endfor %}
</table>

            
{% endblock cuerpo %}

            