mobike/administrativo/urls.py
from django.urls import path
from administrativo.views import *

app_name='administrativo'

urlpatterns = [
    path('administrador_usuarios/', administrador_usuarios, name='administrador_usuarios'),
    path('iniciar_sesion/', iniciar_sesion, name='iniciar_sesion'),
    path('perfil/', perfil, name="perfil"),
    path('administracion_usuarios/', administrador_usuarios, name='administracion_usuarios'),
    path('eliminar_cliente/<int:id>', eliminar_cliente, name='eliminar_cliente'),
    path('editar_usuario/<int:id>', editar_usuario, name='editar_usuario'),
    path('buscar_id/', buscar_id, name='buscar_id'),
    path('registrar_usuario/', registrar_usuario, name="registrar_usuario"),
    path('registrar_administrativo/', registrar_administrativo, name="registrar_administrativo"),
    path('ver_administrativos/', ver_administrativos, name="ver_administrativos"),
    path('cerrar_sesion/', cerrar_sesion, name="cerrar_sesion"),
]

mobike/cliente/urls.py
from django.urls import path
from cliente.views import *

app_name='cliente'

urlpatterns = [
    path('', inicio, name='inicio'),
    path('registrar_usuario/', registrar_usuario, name='registrar_usuario'),
    path('iniciar_sesion/', iniciar_sesion, name='iniciar_sesion'),
    path('perfil/', perfil, name="perfil"),
    path('editar_datos/<int:id>', editar_datos, name="editar_datos"),
    path('cambiar_tarjeta/<int:id>', cambiar_tarjeta, name="cambiar_tarjeta"),
    path('cambiar_contrasena/<int:id>', cambiar_contrasena, name="cambiar_contrasena"),
    path('cerrar_sesion/', cerrar_sesion, name="cerrar_sesion"),

]

mobike/mobike/urls.py
from django.contrib import admin
from django.urls import path, include
from cliente.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cliente.urls')),
    path('administrativo/', include('administrativo.urls')),
]

mobike/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MOBIKE</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'cliente:inicio' %}" style="color: red;"> <u>MOBIKE</u></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        {% block linknav %}
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'cliente:inicio' %}">Inicio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'cliente:registrar_usuario' %}">Registrarse</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'cliente:iniciar_sesion' %}">Iniciar Sesión</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'administrativo:iniciar_sesion' %}">Acceso Administrativo</a>
            </li>
          </ul>
        </div>
        {% endblock linknav %}
      </nav>


    {% block cuerpo %}

      <h1>BASE</h1>

    {% endblock cuerpo %}
</body>
</html>

mobike/templates/inicio.html
{% extends 'base.html' %}

{% block cuerpo %}

<style>
    .botoninicio{
        text-decoration: none;
        color: white;
        display: inline-block;
    }
    .botoninicio:hover{
        text-decoration: none;
        color: white;
    }
</style>



{% if sesion_cerrada %}
<div class="alert alert-danger" role="alert">Sesión Finalizada
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}
<div class="col-12 text-center"><h4>Bienvenido a MOBIKE</h4></div>
<hr>
<div class="row">
    <div class="col-2"></div>
    <div class="col-8">
        Miles de bicicletas disponibles a tu alrededor. ¡Finaliza el recorrido en cualquier estacionamiento para bicicletas que esté cerca de tu lugar de destino. Ya no tendrás que acarrear tu propia bicicleta a todos lados ni viajar apretado en los autobuses. ¡Simplemente usa Mobike para llegar a donde quieras!
        <hr>
    </div>
    <div class="col-2"></div>
</div>
<br>
<div class="row">
    <div class="col-2"></div>
    <div class="col-8 text-center">
        <button class="btn btn-primary">
            <a href="{% url 'cliente:iniciar_sesion' %}" class="botoninicio">Iniciar Sesión</a>
        </button><br>
        <small><a href="{% url 'cliente:registrar_usuario' %}">¿No tienes cuenta? Registrate</a></small>
    </div>
    <div class="col-2"></div>
    
</div>
{% endblock cuerpo %}